file_format: "1"
id: sofle
name: Sofle
type: shield
url: https://github.com/shouldnt/sofle-config/tree/main
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
  - underglow
  - studio
siblings:
  - sofle_left
  - sofle_right
